name: Build, Check And Deploy to Dev

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'

    - name: npm install, and build
      run: |
        printf "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}" >> ~/.npmrc
        npm install
        npm run build
      env:
        FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

    - name: Deploy to Dev s3
      run: |
        aws s3 sync dist s3://$AWS_S3_BUCKET --region us-east-1 --delete
      env:
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_S3_BUCKET: property-data-explorer
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # - name: Notify Slack (UI Test Deployment Completed)
    #   uses: rtCamp/action-slack-notify@master
    #   env:
    #     SLACK_CHANNEL: prj-inmate-locator
    #     SLACK_USERNAME: deployBot
    #     SLACK_ICON: ":scream:"
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    #     SLACK_TITLE: "Completed deployment to UI test and deploy:"
